### ISSUE TITLE
-date parameter handling error

### ISSUE THREAD

**Issue by TariqBlecher** [radio-astro/simms#24]
So I run 

 simms -T VLBA -t casa -n timetest2.MS -dec 0.216265686869rad -ra 3.27608481687rad -st 2 -dt 100 -f0 87GHz -df 1GHz -stl -el 0.17  vlba_antenna/ -date 2013/06/04/00:20:22

and in the output there is the line

015-11-15 19:36:35  INFO    NewMSSimulator::observe()+  Full time range: 04-Jun-2013/10:42:55.0 -- 04-Jun-2013/12:42:55.0 TAI with int = 100

The incorrect time is also written in the MS column TIME.

**Comment by rdeane** [comment]
This bug still seems to be there I'm afraid. 

simms -T VLBA -t casa -n SgrA40muas.MS -dec -29.007810556deg -ra 266.416837083deg -st 24.000000 -sl 24.000000 -slg 0.000000 -dt 10 -f0 228.000000GHz -df 0.250000GHz -nc 16  -date UTC,2017/04/01/00:00:00.00 ../input/EHT_ANTENNAtable

results in an MS with date/time start time of 31-Mar-2017/15:31:06.6  (UTC), as reported by CASA v4.7.

**Comment by rdeane** [comment]
something very strange going on here, check out the attached table. Using simms, I've simulated 8 MSs in 3 hour increments, starting at 2017/04/01/00:00:00. 

Using the listobs task (CASA v4.7), I grab the date time info which is listed in the second column. Does this give an additional clue as to the problem here? 


![screen shot 2017-02-21 at 9 39 20 am](https://cloud.githubusercontent.com/assets/4046151/23155028/767360a2-f819-11e6-8498-e0733d9549af.png)

**Comment by SpheMakh** [comment]
I think something is going wrong with the way I'm parsing the date to CASA simulator.

**Comment by SpheMakh** [comment]
Fixed in the release (0.9.4). Update (`pip install simms --upgrade`) and it should simulate the observation at the specified time instead of trying to start the observation at transit.

**Comment by rdeane** [comment]
Great, all seems to be working. Out of interest, why does CASA arbitrarily add an extra 37 seconds to the start time? I tried it for a start time in April 2017 and July 2017, and both start 37 seconds later than  specified. Just curious...

**Comment by SpheMakh** [comment]
I was wondering about the same thing. I'll play around with this a bit more, and maybe I can figure it out.

**Comment by TariqBlecher** [comment]
It might be to do with leap seconds which I think are mild calendar
alterations between TAI and UTC.. But just guessing
