### ISSUE TITLE
Autocorrelation part of the Measurement set

### ISSUE THREAD

**Issue by Ermiasabebe** [radio-astro/simms#28]
I have been using simms module for generating MS and simulation. The measurement set produced has not auto-correlation part. I attached the snapshot of the table produced using simms. 

Actually we can produce the the auto- correlation  using "makems.cfg" by setting  WriteAutoCorr=T. Maybe WriteAutoCorr=T is not included in simms as a default ?

![autocorrelation](https://cloud.githubusercontent.com/assets/11074927/12832510/1beb553e-cba3-11e5-9995-3aeac3b489aa.png)

**Comment by SpheMakh** [comment]
Thanks for pointing this out. I've added a new option to allow you to include autocorrelations: `-ac/--auto-correlations` on the command line, or `auto_corr` from python.
