### ISSUE TITLE
output columns to simulate

### ISSUE THREAD

**Issue by rdeane** [radio-astro/simms#38]
It would be great if simms gives the option of only simulating 1 output column (i.e. DATA), not automatically include MODEL_DATA and CORRECTED_DATA.

**Comment by SpheMakh** [comment]
Yes, this would be a nice feature, but from a quick glance at the casa simulator tool, it doesn't look its possible. 

As a workaround, I could add a flag ('--data-only') that would trigger a casa 'split' task to get only one coulmn and delete the 'original' ms.

**Comment by rdeane** [comment]
ah, no need - will just do manually. Thanks.
